[build-system]
requires = ["setuptools==63.4.3"]
build-backend = "setuptools.build_meta"

[project]
name = "autonity.py"
version = "0.0.2"
dependencies = [
  "web3==5.28.0"
]

[tool.setuptools.packages.find]
where = [ "." ]
exclude = [ "tests" ]

[tool.setuptools.package-data]
"autonity" = [ "abi/*.abi", "py.typed" ]

[project.optional-dependencies]
"dev" = [
  "mypy==0.982",
  "pylint==2.15.4",
  "flake8==5.0.4",
  "black==19.3b0",
]

[tool.black]
